name: New Merge to main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if PR was merged
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::set-output name=merged::true"
          else
            echo "::set-output name=merged::false"
          fi
        id: check_merged

      - name: Notify on new merge to main
        if: |
          steps.check_merged.outputs.merged == 'true' ||
          (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: echo "A new merge or direct push has been made to the main branch!"
